replicaCount: 1

image:
  repository: aaronshaf/dynamodb-admin
  tag: latest
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 8001

env:
  DYNAMO_ENDPOINT: "http://localstack.localstack.svc.cluster.local:4566"
  AWS_REGION: "eu-central-1"
  AWS_ACCESS_KEY_ID: "test"
  AWS_SECRET_ACCESS_KEY: "test"

resources:
  limits:
    memory: "128Mi"
    cpu: "100m"
  requests:
    memory: "64Mi"
    cpu: "50m" 